namePrefix: capi-

commonLabels:
  cluster.x-k8s.io/provider: "cluster-api"

bases:
- crd
- webhook
- default

patchesJson6902:
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: clusters.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: machinedeployments.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: machines.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: machinesets.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
- target:
    group: apiextensions.k8s.io
    version: v1
    kind: CustomResourceDefinition
    name: machinehealthchecks.cluster.x-k8s.io
  path: patch_crd_webhook_namespace.yaml
