package main

import (
	"fmt"
	"net/http"
	"strings"
)

func main() {

	// Generated by curl-to-Go: https://mholt.github.io/curl-to-go

	body := strings.NewReader(`{"auth":{"passwordCredentials":{"username":"ConoHa","password":"paSSword123456#$%"},"tenantId":"487727e3921d44e3bfe7ebb337bf085e"}}`)
	req, err := http.NewRequest("POST", "https://identity.tyo1.conoha.io/v2.0/tokens", body)
	if err != nil {
		// handle err
	}
	req.Header.Set("Accept", "application/json")
	req.Header.Set("Content-Type", "application/x-www-form-urlencoded")

	resp, err := http.DefaultClient.Do(req)
	if err != nil {
		// handle err
	}
	fmt.Println(resp)
	defer resp.Body.Close()
}
